blank_issues_enabled: false
contact_links:
  - name: Super Web Share Support
    url: https://superwebshare.com/contact/
    about: Customer experience for SuperWebShare users having questions or seeking general support.
  - name: Super Web Share Documentation
    url: https://superwebshare.com/docs/
    about: Information and documentation about Super Web Share.
